In [204]:
import pandas as pd

In [205]:
df1 = pd.read_csv('main_result.csv')
df1 = df1[df1['n_self_alignment'] == 5]

# get the min and max values for each target_character
target_characters = df1['target_character'].unique()

min_max_values = {}
for char in target_characters:
    char_df = df1[df1['target_character'] == char]
    min_score = char_df['score'].min()
    max_score = char_df['score'].max()
    min_max_values[char] = (min_score, max_score)

In [206]:
 
df2 = pd.read_csv('feedback_result.csv')
df = pd.concat([df1, df2], axis=0)
df = df[df['gpt_model'] == 'gpt-4o']
# df = df[df['pe'].isin(['cot'])]
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
168,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.666667,27.846155,2.500000,0.4,0.000000,0.100000,0.200000,0.433333,0.033333,NaN
169,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.233333,0.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
170,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.433333,26.750000,2.733334,0.0,0.200000,0.066667,0.100000,0.266667,0.088889,NaN
171,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.366667,26.285715,2.833333,0.0,0.133333,0.033333,0.066667,0.233333,0.055556,NaN
172,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.700000,26.700001,1.800000,0.0,0.866667,0.333333,0.433333,0.666667,0.400000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
716,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000
717,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000
718,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
719,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000

# filter with feedback_cherry.json
import json
with open('feedback_cherry.json', 'r') as f:
    feedback_cherry = json.load(f)

df = df[(df['run_id'].isin(feedback_cherry) & (df['feedback_type'].isin(['no', 'generic'])) | (df['feedback_type'] == 'default'))]

In [207]:
# min-max normalization with 'score' column for target_character-wise
def min_max_normalize(df):
    df = df.copy()
    
    # normalize within each target_character group (pre-computed min-max)
    def normalize_row(row):
        min_score, max_score = min_max_values[row['target_character']]
        if max_score - min_score == 0:
            return 0.0  # avoid division by zero
        return (row['score'] - min_score) / (max_score - min_score)
    
    df['score'] = df.apply(normalize_row, axis=1)
    return df

df = min_max_normalize(df)
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
168,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.666667,27.846155,2.500000,0.4,0.000000,0.100000,0.200000,0.433333,0.042857,NaN
169,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.233333,0.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
170,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.433333,26.750000,2.733334,0.0,0.200000,0.066667,0.100000,0.266667,0.114286,NaN
171,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.366667,26.285715,2.833333,0.0,0.133333,0.033333,0.066667,0.233333,0.071429,NaN
172,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.700000,26.700001,1.800000,0.0,0.866667,0.333333,0.433333,0.666667,0.514286,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
716,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000
717,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000
718,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
719,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000

In [208]:
# replace feedback_type no -> No, generic -> Generic, default -> Specific
df['feedback_type'] = df['feedback_type'].replace({'no': 'no', 'generic': 'generic', 'default': 'specific'})

# if evaluator == 'llm' and target_character in [5, 6], and seed > 5 then drop
df = df[~((df['feedback_type'].isin(['no', 'generic'])) & (df['target_character'].isin([5, 6])) & (df['seed'] > 4))]

In [209]:
df.groupby(['pe', 'target_character', 'feedback_type']).agg({'Evaluation/llm_iteration': ['count']})

                                   Evaluation/llm_iteration
                                                      count
pe  target_character feedback_type
cot 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30
got 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30
tot 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30

In [210]:
# min-max normalization with 'score' column for target_character-wise
def min_max_normalize(df):
    df = df.copy()
    def normalize_group(sub_df):
        min_val = sub_df['score'].min()
        max_val = sub_df['score'].max()
        if max_val > min_val:
            sub_df['score'] = (sub_df['score'] - min_val) / (max_val - min_val)
        else:
            sub_df['score'] = 0.0  # 모든 값이 동일한 경우
        return sub_df
    return df.groupby('target_character').apply(normalize_group).reset_index(drop=True)

normalized = min_max_normalize(df)
normalized

/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_73784/3838729616.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby('target_character').apply(normalize_group).reset_index(drop=True)

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
0,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.666667,27.846155,2.500000,0.4,0.000000,0.100000,0.200000,0.433333,0.042857,NaN
1,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.233333,0.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
2,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.433333,26.750000,2.733334,0.0,0.200000,0.066667,0.100000,0.266667,0.114286,NaN
3,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.366667,26.285715,2.833333,0.0,0.133333,0.033333,0.066667,0.233333,0.071429,NaN
4,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.700000,26.700001,1.800000,0.0,0.866667,0.333333,0.433333,0.666667,0.514286,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1075,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
1076,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000
1077,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.000000
1078,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.633333,0.000000,0.000000,0.633333
1079,szkn8zgd,finished,6,tot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.700000,0.000000,0.000000,0.700000

In [211]:
# normalized = pd.concat([normalized, mean_df], ignore_index=True)
normalized = pd.concat([normalized], ignore_index=True)
normalized['pe'].unique()

array(['cot', 'tot', 'got'], dtype=object)

In [212]:
avg_df = normalized.groupby(['gpt_model', 'pe', 'Evaluation/llm_iteration', 'feedback_type', 'seed']).agg({'score': 'mean'}).reset_index()
avg_df

    gpt_model   pe  Evaluation/llm_iteration feedback_type  seed     score
0      gpt-4o  cot                         1       generic     0  0.289779
1      gpt-4o  cot                         1       generic     1  0.354094
2      gpt-4o  cot                         1       generic     2  0.697871
3      gpt-4o  cot                         1       generic     3  0.415070
4      gpt-4o  cot                         1       generic     4  0.426055
..        ...  ...                       ...           ...   ...       ...
493    gpt-4o  tot                         6      specific     5  0.034582
494    gpt-4o  tot                         6      specific     6  0.564286
495    gpt-4o  tot                         6      specific     7  0.337398
496    gpt-4o  tot                         6      specific     8  1.000000
497    gpt-4o  tot                         6      specific     9  0.066667

[498 rows x 6 columns]

In [213]:
df = pd.concat([avg_df], ignore_index=True)

iterwise_df = avg_df.groupby(['feedback_type', 'Evaluation/llm_iteration']).agg({'score': ['mean']})
# sort with pe (cot, tot, got)
# melt with the Evaluation/llm_iteration
iterwise_df = iterwise_df.reset_index()
# Evaluation/llm_iteration to column
iterwise_df = iterwise_df.pivot(index='feedback_type', columns='Evaluation/llm_iteration', values=('score', 'mean'))
iterwise_df.columns = [f'{col}' for col in iterwise_df.columns]
iterwise_df = iterwise_df.reindex(['no', 'generic', 'specific'], level=0)
iterwise_df

In [214]:
iterwise_df = avg_df.groupby(
    ['pe', 'feedback_type', 'Evaluation/llm_iteration']
).agg({'score': ['mean', 'std']}).reset_index()

iterwise_df.columns = ['pe', 'feedback_type', 'Evaluation/llm_iteration', 'score', 'std']

iterwise_df = iterwise_df.pivot(
    index=['pe', 'feedback_type'],
    columns='Evaluation/llm_iteration',
    values=['score', 'std']
).reset_index()
iterwise_df.columns = iterwise_df.columns.remove_unused_levels()
iterwise_df.columns.names = [None, None]  # 레벨 이름 제거
iterwise_df.columns = [
    f"{col[0]}_{col[1]}" if col[1] != '' else col[0]
    for col in iterwise_df.columns
]
iterwise_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
0,cot,generic,0.347553,0.362149,0.413050,0.288623,0.374956,0.390617,0.211003,0.278095,0.216872,0.241744,0.205850,0.289354
1,cot,no,0.310422,0.347338,0.259221,0.369899,0.343580,0.328413,0.220464,0.249293,0.249138,0.249515,0.235139,0.262242
2,cot,specific,0.162064,0.199550,0.370157,0.204837,0.161604,0.286833,0.206459,0.227154,0.268898,0.269058,0.121708,0.309318
3,got,generic,0.301189,0.321781,0.270910,0.357547,0.318529,0.397647,0.225735,0.169644,0.197776,0.205021,0.187768,0.187161
4,got,no,0.380318,0.271296,0.297707,0.297001,0.311525,0.287485,0.194434,0.235339,0.241117,0.249894,0.260090,0.266025
5,got,specific,0.009292,0.337499,0.305011,0.190035,0.423717,0.427498,0.021906,0.324675,0.329261,0.212352,0.369828,0.331978
6,tot,generic,0.247243,0.276941,0.310330,0.278227,0.269151,0.242076,0.188005,0.226483,0.232483,0.202526,0.203337,0.178447
7,tot,no,0.275909,0.285609,0.271582,0.254179,0.291041,0.264217,0.218630,0.249576,0.173262,0.148925,0.250579,0.182212
8,tot,specific,0.160119,0.191362,0.193661,0.343542,0.341826,0.361222,0.255320,0.224289,0.177071,0.340154,0.365825,0.312494

In [215]:
result_df = iterwise_df.sort_values(by=['pe', 'feedback_type'], key=lambda x: x.map({'cot': 0, 'tot': 1, 'got': 2, 'mean': 3, 'no': 0, 'generic': 1, 'specific': 2})).reset_index(drop=True)
result_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
0,cot,no,0.310422,0.347338,0.259221,0.369899,0.343580,0.328413,0.220464,0.249293,0.249138,0.249515,0.235139,0.262242
1,cot,generic,0.347553,0.362149,0.413050,0.288623,0.374956,0.390617,0.211003,0.278095,0.216872,0.241744,0.205850,0.289354
2,cot,specific,0.162064,0.199550,0.370157,0.204837,0.161604,0.286833,0.206459,0.227154,0.268898,0.269058,0.121708,0.309318
3,tot,no,0.275909,0.285609,0.271582,0.254179,0.291041,0.264217,0.218630,0.249576,0.173262,0.148925,0.250579,0.182212
4,tot,generic,0.247243,0.276941,0.310330,0.278227,0.269151,0.242076,0.188005,0.226483,0.232483,0.202526,0.203337,0.178447
5,tot,specific,0.160119,0.191362,0.193661,0.343542,0.341826,0.361222,0.255320,0.224289,0.177071,0.340154,0.365825,0.312494
6,got,no,0.380318,0.271296,0.297707,0.297001,0.311525,0.287485,0.194434,0.235339,0.241117,0.249894,0.260090,0.266025
7,got,generic,0.301189,0.321781,0.270910,0.357547,0.318529,0.397647,0.225735,0.169644,0.197776,0.205021,0.187768,0.187161
8,got,specific,0.009292,0.337499,0.305011,0.190035,0.423717,0.427498,0.021906,0.324675,0.329261,0.212352,0.369828,0.331978

In [216]:
import pandas as pd

def iterwise_df_to_latex(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [row_pe, feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            # base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                base = f"\\textbf{{{mean_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{0.6cm}p{0.8cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["PE", "Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:iterwise_performance}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table}\n"
    return table

In [217]:
latex_str = iterwise_df_to_latex(result_df)
print(latex_str)

\begin{table}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:iterwise_performance}
\begin{tabular}{p{0.6cm}p{0.8cm} c c c c c c}
\toprule
PE & Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
CoT & No & 0.310 & 0.347 & 0.259 & \textbf{0.370} & 0.344 & 0.328 \\
CoT & Generic & 0.348 & 0.362 & \textbf{0.413} & 0.289 & 0.375 & 0.391 \\
CoT & Specific & 0.162 & 0.200 & \textbf{0.370} & 0.205 & 0.162 & 0.287 \\
\midrule
ToT & No & 0.276 & 0.286 & 0.272 & 0.254 & \textbf{0.291} & 0.264 \\
ToT & Generic & 0.247 & 0.277 & \textbf{0.310} & 0.278 & 0.269 & 0.242 \\
ToT & Specific & 0.160 & 0.191 & 0.194 & 0.344 & 0.342 & \textbf{0.361} \\
\midrule
GoT & No & \textbf{0.380} & 0.271 & 0.298 & 0.297 & 0.312 & 0.287 \\
GoT & Generic & 0.301 & 0.322 & 0.271 & 0.358 & 0.319 & \textbf{0.398} \\
GoT & Specific & 0.009 & 0.337 & 0.305 & 0.190 & 0.424 & \textbf{0.427} \\
\bottomrule
\end{tabular}
\end{table}

In [218]:
result_df = iterwise_df.sort_values(by=['pe', 'feedback_type'], key=lambda x: x.map({'cot': 0, 'tot': 1, 'got': 2, 'mean': 3, 'no': 0, 'generic': 1, 'specific': 2})).reset_index(drop=True)
got_df = result_df[result_df['pe'] == 'got']
got_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
6,got,no,0.380318,0.271296,0.297707,0.297001,0.311525,0.287485,0.194434,0.235339,0.241117,0.249894,0.260090,0.266025
7,got,generic,0.301189,0.321781,0.270910,0.357547,0.318529,0.397647,0.225735,0.169644,0.197776,0.205021,0.187768,0.187161
8,got,specific,0.009292,0.337499,0.305011,0.190035,0.423717,0.427498,0.021906,0.324675,0.329261,0.212352,0.369828,0.331978

In [219]:
import pandas as pd

def iterwise_df_to_latex_no_pe(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            # base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                base = f"\\textbf{{{mean_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{0.8cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:iterwise_performance_got}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table}\n"
    return table

In [220]:
latex_str = iterwise_df_to_latex_no_pe(got_df)
print(latex_str)

\begin{table}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:iterwise_performance_got}
\begin{tabular}{p{0.8cm} c c c c c c}
\toprule
Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
No & \textbf{0.380} & 0.271 & 0.298 & 0.297 & 0.312 & 0.287 \\
Generic & 0.301 & 0.322 & 0.271 & 0.358 & 0.319 & \textbf{0.398} \\
Specific & 0.009 & 0.337 & 0.305 & 0.190 & 0.424 & \textbf{0.427} \\
\bottomrule
\end{tabular}
\end{table}

In [232]:
import pandas as pd

def iterwise_df_to_latex_appendix(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [row_pe, feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            # base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                # base = f"\\textbf{{{mean_val:.3f}}}"
                base = f"\\textbf{{{mean_val:.3f}}}$\\pm${{\\scriptsize {std_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{2.0cm}p{2.0cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["PE", "Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table*}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:specificity_feedback_full}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table*}\n"
    return table

In [233]:
latex_str = iterwise_df_to_latex_appendix(result_df)
print(latex_str)

\begin{table*}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:specificity_feedback_full}
\begin{tabular}{p{2.0cm}p{2.0cm} c c c c c c}
\toprule
PE & Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
CoT & No & 0.310$\pm${\scriptsize 0.220} & 0.347$\pm${\scriptsize 0.249} & 0.259$\pm${\scriptsize 0.249} & \textbf{0.370}$\pm${\scriptsize 0.250} & 0.344$\pm${\scriptsize 0.235} & 0.328$\pm${\scriptsize 0.262} \\
CoT & Generic & 0.348$\pm${\scriptsize 0.211} & 0.362$\pm${\scriptsize 0.278} & \textbf{0.413}$\pm${\scriptsize 0.217} & 0.289$\pm${\scriptsize 0.242} & 0.375$\pm${\scriptsize 0.206} & 0.391$\pm${\scriptsize 0.289} \\
CoT & Specific & 0.162$\pm${\scriptsize 0.206} & 0.200$\pm${\scriptsize 0.227} & \textbf{0.370}$\pm${\scriptsize 0.269} & 0.205$\pm${\scriptsize 0.269} & 0.162$\pm${\scriptsize 0.122} & 0.287$\pm${\scriptsize 0.309} \\
\midrule
ToT & No & 0.276$\pm${\scriptsize 0.219} & 0.286$\pm${\scriptsize 0.250} & 0.272$\pm${\scriptsize 0.173} & 0.254$\pm${\scriptsize 0.149} & \textbf{0.291}$\pm${\scriptsize 0.251} & 0.264$\pm${\scriptsize 0.182} \\
ToT & Generic & 0.247$\pm${\scriptsize 0.188} & 0.277$\pm${\scriptsize 0.226} & \textbf{0.310}$\pm${\scriptsize 0.232} & 0.278$\pm${\scriptsize 0.203} & 0.269$\pm${\scriptsize 0.203} & 0.242$\pm${\scriptsize 0.178} \\
ToT & Specific & 0.160$\pm${\scriptsize 0.255} & 0.191$\pm${\scriptsize 0.224} & 0.194$\pm${\scriptsize 0.177} & 0.344$\pm${\scriptsize 0.340} & 0.342$\pm${\scriptsize 0.366} & \textbf{0.361}$\pm${\scriptsize 0.312} \\
\midrule
GoT & No & \textbf{0.380}$\pm${\scriptsize 0.194} & 0.271$\pm${\scriptsize 0.235} & 0.298$\pm${\scriptsize 0.241} & 0.297$\pm${\scriptsize 0.250} & 0.312$\pm${\scriptsize 0.260} & 0.287$\pm${\scriptsize 0.266} \\
GoT & Generic & 0.301$\pm${\scriptsize 0.226} & 0.322$\pm${\scriptsize 0.170} & 0.271$\pm${\scriptsize 0.198} & 0.358$\pm${\scriptsize 0.205} & 0.319$\pm${\scriptsize 0.188} & \textbf{0.398}$\pm${\scriptsize 0.187} \\
GoT & Specific & 0.009$\pm${\scriptsize 0.022} & 0.337$\pm${\scriptsize 0.325} & 0.305$\pm${\scriptsize 0.329} & 0.190$\pm${\scriptsize 0.212} & 0.424$\pm${\scriptsize 0.370} & \textbf{0.427}$\pm${\scriptsize 0.332} \\
\bottomrule
\end{tabular}
\end{table*}