In [168]:
import pandas as pd

In [169]:
df1 = pd.read_csv('main_result.csv')
df1 = df1[df1['n_self_alignment'] == 5]

# get the min and max values for each target_character
target_characters = df1['target_character'].unique()

min_max_values = {}
for char in target_characters:
    char_df = df1[df1['target_character'] == char]
    min_score = char_df['score'].min()
    max_score = char_df['score'].max()
    min_max_values[char] = (min_score, max_score)

In [170]:
 
df2 = pd.read_csv('feedback_result.csv')
df = pd.concat([df1, df2], axis=0)
df = df[df['gpt_model'] == 'gpt-4o']
# df = df[df['pe'].isin(['cot'])]
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
168,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.666667,27.846155,2.500000,0.4,0.000000,0.100000,0.200000,0.433333,0.033333,NaN
169,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.233333,0.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
170,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.433333,26.750000,2.733334,0.0,0.200000,0.066667,0.100000,0.266667,0.088889,NaN
171,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.366667,26.285715,2.833333,0.0,0.133333,0.033333,0.066667,0.233333,0.055556,NaN
172,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.700000,26.700001,1.800000,0.0,0.866667,0.333333,0.433333,0.666667,0.400000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
716,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
717,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
718,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
719,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.333333,0.000000,0.000000,0.333333

# filter with feedback_cherry.json
import json
with open('feedback_cherry.json', 'r') as f:
    feedback_cherry = json.load(f)

df = df[(df['run_id'].isin(feedback_cherry) & (df['feedback_type'].isin(['no', 'generic'])) | (df['feedback_type'] == 'default'))]

In [171]:
# min-max normalization with 'score' column for target_character-wise
def min_max_normalize(df):
    df = df.copy()
    
    # normalize within each target_character group (pre-computed min-max)
    def normalize_row(row):
        min_score, max_score = min_max_values[row['target_character']]
        if max_score - min_score == 0:
            return 0.0  # avoid division by zero
        return (row['score'] - min_score) / (max_score - min_score)
    
    df['score'] = df.apply(normalize_row, axis=1)
    return df

df = min_max_normalize(df)
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
168,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.666667,27.846155,2.500000,0.4,0.000000,0.100000,0.200000,0.433333,0.042857,NaN
169,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.233333,0.000000,3.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,NaN
170,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.433333,26.750000,2.733334,0.0,0.200000,0.066667,0.100000,0.266667,0.114286,NaN
171,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.366667,26.285715,2.833333,0.0,0.133333,0.033333,0.066667,0.233333,0.071429,NaN
172,3kk20v1f,finished,1,cot,gpt-4o,2,sa,hr,6,5,...,0.700000,26.700001,1.800000,0.0,0.866667,0.333333,0.433333,0.666667,0.514286,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
716,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
717,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
718,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000
719,fsbq98kh,finished,6,cot,gpt-4o,2,feedback,hr,6,5,...,NaN,NaN,NaN,NaN,NaN,NaN,0.333333,0.000000,0.000000,0.333333

In [172]:
# replace feedback_type no -> No, generic -> Generic, default -> Specific
df['feedback_type'] = df['feedback_type'].replace({'no': 'no', 'generic': 'generic', 'default': 'specific'})

# if evaluator == 'llm' and target_character in [5, 6], and seed > 5 then drop
df = df[~((df['feedback_type'].isin(['no', 'generic'])) & (df['target_character'].isin([5, 6])) & (df['seed'] > 4))]

In [173]:
df.groupby(['pe', 'target_character', 'feedback_type']).agg({'Evaluation/llm_iteration': ['count']})

                                   Evaluation/llm_iteration
                                                      count
pe  target_character feedback_type
cot 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30
got 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30
tot 1                generic                             30
                     no                                  30
                     specific                            30
    2                generic                             30
                     no                                  30
                     specific                            30
    5                generic                             30
                     no                                  30
                     specific                            30
    6                generic                             30
                     no                                  30
                     specific                            30

In [174]:
# normalized = pd.concat([normalized, mean_df], ignore_index=True)
normalized = pd.concat([df], ignore_index=True)
normalized['pe'].unique()

array(['cot', 'tot', 'got'], dtype=object)

In [175]:
avg_df = normalized.groupby(['gpt_model', 'pe', 'Evaluation/llm_iteration', 'feedback_type', 'seed']).agg({'score': 'mean'}).reset_index()
avg_df

    gpt_model   pe  Evaluation/llm_iteration feedback_type  seed     score
0      gpt-4o  cot                         1       generic     0  0.214286
1      gpt-4o  cot                         1       generic     1  0.343254
2      gpt-4o  cot                         1       generic     2  0.644444
3      gpt-4o  cot                         1       generic     3  0.304762
4      gpt-4o  cot                         1       generic     4  0.166667
..        ...  ...                       ...           ...   ...       ...
505    gpt-4o  tot                         6      specific     5  0.032143
506    gpt-4o  tot                         6      specific     6  0.564286
507    gpt-4o  tot                         6      specific     7  0.337037
508    gpt-4o  tot                         6      specific     8  1.000000
509    gpt-4o  tot                         6      specific     9  0.066667

[510 rows x 6 columns]

In [176]:
df = pd.concat([avg_df], ignore_index=True)

iterwise_df = avg_df.groupby(['feedback_type', 'Evaluation/llm_iteration']).agg({'score': ['mean']})
# sort with pe (cot, tot, got)
# melt with the Evaluation/llm_iteration
iterwise_df = iterwise_df.reset_index()
# Evaluation/llm_iteration to column
iterwise_df = iterwise_df.pivot(index='feedback_type', columns='Evaluation/llm_iteration', values=('score', 'mean'))
iterwise_df.columns = [f'{col}' for col in iterwise_df.columns]
iterwise_df = iterwise_df.reindex(['no', 'generic', 'specific'], level=0)
iterwise_df

In [177]:
iterwise_df = avg_df.groupby(
    ['pe', 'feedback_type', 'Evaluation/llm_iteration']
).agg({'score': ['mean', 'std']}).reset_index()

iterwise_df.columns = ['pe', 'feedback_type', 'Evaluation/llm_iteration', 'score', 'std']

iterwise_df = iterwise_df.pivot(
    index=['pe', 'feedback_type'],
    columns='Evaluation/llm_iteration',
    values=['score', 'std']
).reset_index()
iterwise_df.columns = iterwise_df.columns.remove_unused_levels()
iterwise_df.columns.names = [None, None]  # 레벨 이름 제거
iterwise_df.columns = [
    f"{col[0]}_{col[1]}" if col[1] != '' else col[0]
    for col in iterwise_df.columns
]
iterwise_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
0,cot,generic,0.343783,0.408392,0.364433,0.390991,0.280556,0.364609,0.207024,0.215668,0.266798,0.269049,0.215840,0.263611
1,cot,no,0.293078,0.327646,0.243563,0.351411,0.325573,0.308510,0.200567,0.227054,0.228011,0.229699,0.215255,0.240314
2,cot,specific,0.161964,0.198266,0.361405,0.202910,0.160259,0.284303,0.206536,0.227282,0.267701,0.269710,0.122780,0.307616
3,got,generic,0.289342,0.308825,0.258031,0.344822,0.305650,0.384845,0.217582,0.163086,0.189531,0.202450,0.180419,0.184488
4,got,no,0.367130,0.256481,0.282440,0.279431,0.295536,0.271616,0.183854,0.219324,0.224706,0.231433,0.242450,0.246676
5,got,specific,0.009171,0.326720,0.301117,0.185097,0.413198,0.422781,0.021891,0.307136,0.328694,0.207816,0.358295,0.328848
6,tot,generic,0.234656,0.263933,0.297443,0.265520,0.256584,0.231658,0.176725,0.213705,0.219954,0.189775,0.193484,0.169694
7,tot,no,0.267532,0.268494,0.258081,0.241270,0.274387,0.249928,0.215886,0.228226,0.160856,0.138219,0.229210,0.168802
8,tot,specific,0.160119,0.184722,0.189325,0.339206,0.337897,0.359696,0.255320,0.219306,0.176161,0.341899,0.367293,0.313119

In [178]:
result_df = iterwise_df.sort_values(by=['pe', 'feedback_type'], key=lambda x: x.map({'cot': 0, 'tot': 1, 'got': 2, 'mean': 3, 'no': 0, 'generic': 1, 'specific': 2})).reset_index(drop=True)
result_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
0,cot,no,0.293078,0.327646,0.243563,0.351411,0.325573,0.308510,0.200567,0.227054,0.228011,0.229699,0.215255,0.240314
1,cot,generic,0.343783,0.408392,0.364433,0.390991,0.280556,0.364609,0.207024,0.215668,0.266798,0.269049,0.215840,0.263611
2,cot,specific,0.161964,0.198266,0.361405,0.202910,0.160259,0.284303,0.206536,0.227282,0.267701,0.269710,0.122780,0.307616
3,tot,no,0.267532,0.268494,0.258081,0.241270,0.274387,0.249928,0.215886,0.228226,0.160856,0.138219,0.229210,0.168802
4,tot,generic,0.234656,0.263933,0.297443,0.265520,0.256584,0.231658,0.176725,0.213705,0.219954,0.189775,0.193484,0.169694
5,tot,specific,0.160119,0.184722,0.189325,0.339206,0.337897,0.359696,0.255320,0.219306,0.176161,0.341899,0.367293,0.313119
6,got,no,0.367130,0.256481,0.282440,0.279431,0.295536,0.271616,0.183854,0.219324,0.224706,0.231433,0.242450,0.246676
7,got,generic,0.289342,0.308825,0.258031,0.344822,0.305650,0.384845,0.217582,0.163086,0.189531,0.202450,0.180419,0.184488
8,got,specific,0.009171,0.326720,0.301117,0.185097,0.413198,0.422781,0.021891,0.307136,0.328694,0.207816,0.358295,0.328848

In [179]:
import pandas as pd

def iterwise_df_to_latex(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [row_pe, feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            # base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                base = f"\\textbf{{{mean_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{0.6cm}p{0.8cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["PE", "Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:iterwise_performance}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table}\n"
    return table

In [180]:
latex_str = iterwise_df_to_latex(result_df)
print(latex_str)

\begin{table}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:iterwise_performance}
\begin{tabular}{p{0.6cm}p{0.8cm} c c c c c c}
\toprule
PE & Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
CoT & No & 0.293 & 0.328 & 0.244 & \textbf{0.351} & 0.326 & 0.309 \\
CoT & Generic & 0.344 & \textbf{0.408} & 0.364 & 0.391 & 0.281 & 0.365 \\
CoT & Specific & 0.162 & 0.198 & \textbf{0.361} & 0.203 & 0.160 & 0.284 \\
\midrule
ToT & No & 0.268 & 0.268 & 0.258 & 0.241 & \textbf{0.274} & 0.250 \\
ToT & Generic & 0.235 & 0.264 & \textbf{0.297} & 0.266 & 0.257 & 0.232 \\
ToT & Specific & 0.160 & 0.185 & 0.189 & 0.339 & 0.338 & \textbf{0.360} \\
\midrule
GoT & No & \textbf{0.367} & 0.256 & 0.282 & 0.279 & 0.296 & 0.272 \\
GoT & Generic & 0.289 & 0.309 & 0.258 & 0.345 & 0.306 & \textbf{0.385} \\
GoT & Specific & 0.009 & 0.327 & 0.301 & 0.185 & 0.413 & \textbf{0.423} \\
\bottomrule
\end{tabular}
\end{table}

In [181]:
result_df = iterwise_df.sort_values(by=['pe', 'feedback_type'], key=lambda x: x.map({'cot': 0, 'tot': 1, 'got': 2, 'mean': 3, 'no': 0, 'generic': 1, 'specific': 2})).reset_index(drop=True)
got_df = result_df[result_df['pe'] == 'got']
got_df

,pe,feedback_type,score_1,score_2,score_3,score_4,score_5,score_6,std_1,std_2,std_3,std_4,std_5,std_6
6,got,no,0.367130,0.256481,0.282440,0.279431,0.295536,0.271616,0.183854,0.219324,0.224706,0.231433,0.242450,0.246676
7,got,generic,0.289342,0.308825,0.258031,0.344822,0.305650,0.384845,0.217582,0.163086,0.189531,0.202450,0.180419,0.184488
8,got,specific,0.009171,0.326720,0.301117,0.185097,0.413198,0.422781,0.021891,0.307136,0.328694,0.207816,0.358295,0.328848

In [182]:
import pandas as pd

def iterwise_df_to_latex_no_pe(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            # base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                base = f"\\textbf{{{mean_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{0.8cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:iterwise_performance_got}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table}\n"
    return table

In [183]:
latex_str = iterwise_df_to_latex_no_pe(got_df)
print(latex_str)

\begin{table}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:iterwise_performance_got}
\begin{tabular}{p{0.8cm} c c c c c c}
\toprule
Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
No & \textbf{0.367} & 0.256 & 0.282 & 0.279 & 0.296 & 0.272 \\
Generic & 0.289 & 0.309 & 0.258 & 0.345 & 0.306 & \textbf{0.385} \\
Specific & 0.009 & 0.327 & 0.301 & 0.185 & 0.413 & \textbf{0.423} \\
\bottomrule
\end{tabular}
\end{table}

In [184]:
import pandas as pd

def iterwise_df_to_latex_appendix(df: pd.DataFrame) -> str:
    """
    iterwise_df를 LaTeX 테이블로 변환.
    - score/std 짝을 mean ± std 로 표시
    - 각 (pe, feedback_type) row에서 최고 score iteration은 mean 부분만 bold
    - 표준편차는 \scriptsize 로 더 작게 표시
    - PE가 바뀔 때마다 \midrule 삽입
    """
    latex_rows = []
    prev_pe = None

    # iteration 번호 추출
    score_cols = sorted([c for c in df.columns if c.startswith("score_")],
                        key=lambda x: int(x.split("_")[1]))
    std_cols = sorted([c for c in df.columns if c.startswith("std_")],
                      key=lambda x: int(x.split("_")[1]))
    iterations = [c.split("_")[1] for c in score_cols]
    
    # $y_{i}$
    iterations = [f"$y_{{{i}}}$" for i in iterations]

    for _, row in df.iterrows():
        row_pe = str(row["pe"]).replace('cot', 'CoT').replace('tot', 'ToT').replace('got', 'GoT').replace('mean', 'Mean')  
        feedback_type = str(row["feedback_type"]).capitalize()
        row_entries = [row_pe, feedback_type]
        # capitalize first letter of feedback_type

        # 최고 score 컬럼 찾기
        best_col = row[score_cols].astype(float).idxmax()

        for s, st in zip(score_cols, std_cols):
            mean_val = row[s]
            std_val = row[st]

            # 기본 표현: mean ± std (std는 작은 글씨)
            base = f"{mean_val:.3f}$\\pm${{\\scriptsize {std_val:.3f}}}"
            # base = f"{mean_val:.3f}"

            # 최고 mean만 bold 처리 (std는 그대로)
            if s == best_col:
                # base = f"\\textbf{{{mean_val:.3f}}}"
                base = f"\\textbf{{{mean_val:.3f}}}$\\pm${{\\scriptsize {std_val:.3f}}}"

            row_entries.append(base)

        # pe가 바뀔 때 midrule 삽입
        if prev_pe is not None and row_pe != prev_pe:
            latex_rows.append("\\midrule")
        prev_pe = row_pe

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # --- colspec (동적으로) ---
    col_spec = "p{2.0cm}p{2.0cm}" + " c" * len(iterations)

    # --- header: iteration 번호만 표시 ---
    header = ["PE", "Feedback"] + iterations

    # --- Table build ---
    table = ""
    table += "\\begin{table*}\n"
    table += "\\centering\n"
    table += "\\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}\n"
    table += "\\label{tab:specificity_feedback_full}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n"
    table += "\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n"
    table += "\\end{tabular}\n"
    table += "\\end{table*}\n"
    return table

In [185]:
latex_str = iterwise_df_to_latex_appendix(result_df)
print(latex_str)

\begin{table*}
\centering
\caption{Iteration-wise performance by PE and feedback type. Highest iteration per row is bold.}
\label{tab:specificity_feedback_full}
\begin{tabular}{p{2.0cm}p{2.0cm} c c c c c c}
\toprule
PE & Feedback & $y_{1}$ & $y_{2}$ & $y_{3}$ & $y_{4}$ & $y_{5}$ & $y_{6}$ \\
\midrule
CoT & No & 0.293$\pm${\scriptsize 0.201} & 0.328$\pm${\scriptsize 0.227} & 0.244$\pm${\scriptsize 0.228} & \textbf{0.351}$\pm${\scriptsize 0.230} & 0.326$\pm${\scriptsize 0.215} & 0.309$\pm${\scriptsize 0.240} \\
CoT & Generic & 0.344$\pm${\scriptsize 0.207} & \textbf{0.408}$\pm${\scriptsize 0.216} & 0.364$\pm${\scriptsize 0.267} & 0.391$\pm${\scriptsize 0.269} & 0.281$\pm${\scriptsize 0.216} & 0.365$\pm${\scriptsize 0.264} \\
CoT & Specific & 0.162$\pm${\scriptsize 0.207} & 0.198$\pm${\scriptsize 0.227} & \textbf{0.361}$\pm${\scriptsize 0.268} & 0.203$\pm${\scriptsize 0.270} & 0.160$\pm${\scriptsize 0.123} & 0.284$\pm${\scriptsize 0.308} \\
\midrule
ToT & No & 0.268$\pm${\scriptsize 0.216} & 0.268$\pm${\scriptsize 0.228} & 0.258$\pm${\scriptsize 0.161} & 0.241$\pm${\scriptsize 0.138} & \textbf{0.274}$\pm${\scriptsize 0.229} & 0.250$\pm${\scriptsize 0.169} \\
ToT & Generic & 0.235$\pm${\scriptsize 0.177} & 0.264$\pm${\scriptsize 0.214} & \textbf{0.297}$\pm${\scriptsize 0.220} & 0.266$\pm${\scriptsize 0.190} & 0.257$\pm${\scriptsize 0.193} & 0.232$\pm${\scriptsize 0.170} \\
ToT & Specific & 0.160$\pm${\scriptsize 0.255} & 0.185$\pm${\scriptsize 0.219} & 0.189$\pm${\scriptsize 0.176} & 0.339$\pm${\scriptsize 0.342} & 0.338$\pm${\scriptsize 0.367} & \textbf{0.360}$\pm${\scriptsize 0.313} \\
\midrule
GoT & No & \textbf{0.367}$\pm${\scriptsize 0.184} & 0.256$\pm${\scriptsize 0.219} & 0.282$\pm${\scriptsize 0.225} & 0.279$\pm${\scriptsize 0.231} & 0.296$\pm${\scriptsize 0.242} & 0.272$\pm${\scriptsize 0.247} \\
GoT & Generic & 0.289$\pm${\scriptsize 0.218} & 0.309$\pm${\scriptsize 0.163} & 0.258$\pm${\scriptsize 0.190} & 0.345$\pm${\scriptsize 0.202} & 0.306$\pm${\scriptsize 0.180} & \textbf{0.385}$\pm${\scriptsize 0.184} \\
GoT & Specific & 0.009$\pm${\scriptsize 0.022} & 0.327$\pm${\scriptsize 0.307} & 0.301$\pm${\scriptsize 0.329} & 0.185$\pm${\scriptsize 0.208} & 0.413$\pm${\scriptsize 0.358} & \textbf{0.423}$\pm${\scriptsize 0.329} \\
\bottomrule
\end{tabular}
\end{table*}