In [4]:
from dotenv import load_dotenv
import pandas as pd
import os

In [5]:
df = pd.read_csv('main_result.csv')
df

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
0,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.533333,26.000002,2.566667,0.400000,0.0,0.033333,0.200000,1.000000,0.011111,NaN
1,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,26.000000,2.666667,0.333333,0.0,0.000000,0.166667,0.966667,0.000000,NaN
2,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.600000,26.214287,2.566667,0.333333,0.0,0.100000,0.166667,0.933333,0.033333,NaN
3,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.133333,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN
4,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.800000,0.000000,0.000000,0.8
1436,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0
1437,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0
1438,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.800000,0.000000,0.000000,0.8
1439,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0

In [6]:
df.groupby(['gpt_model', 'pe', 'target_character', 'n_self_alignment']).agg({'Evaluation/llm_iteration': ['count']})

                                                Evaluation/llm_iteration
                                                                   count
gpt_model pe  target_character n_self_alignment
gpt-4o    cot 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30
          got 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30
          tot 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30
llama-32  cot 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30
          got 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30
          tot 1                0                                      30
                               5                                      30
              2                0                                      30
                               5                                      30
              5                0                                      30
                               5                                      30
              6                0                                      30
                               5                                      30

In [7]:
# min-max normalization with 'score' column for target_character-wise
def min_max_normalize(df):
    df = df.copy()
    def normalize_group(sub_df):
        min_val = sub_df['score'].min()
        max_val = sub_df['score'].max()
        if max_val > min_val:
            sub_df['score'] = (sub_df['score'] - min_val) / (max_val - min_val)
        else:
            sub_df['score'] = 0.0  # 모든 값이 동일한 경우
        return sub_df
    return df.groupby('target_character').apply(normalize_group).reset_index(drop=True)

normalized = min_max_normalize(df)
normalized

/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/3838729616.py:12: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  return df.groupby('target_character').apply(normalize_group).reset_index(drop=True)

,run_id,final_state,target_character,pe,gpt_model,branch_factor,exp_name,evaluator,total_iterations,n_self_alignment,...,Evaluation/reach_imp_perc,Evaluation/path_length,Evaluation/fn_imp_perc,Evaluation/fp_imp_perc,Evaluation/tn_imp_perc,Evaluation/tp_imp_perc,Evaluation/solvability,Evaluation/playability,score,Evaluation/naive_playability
0,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.533333,26.000002,2.566667,0.400000,0.0,0.033333,0.200000,1.000000,0.012048,NaN
1,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,26.000000,2.666667,0.333333,0.0,0.000000,0.166667,0.966667,0.000000,NaN
2,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.600000,26.214287,2.566667,0.333333,0.0,0.100000,0.166667,0.933333,0.036145,NaN
3,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.133333,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN
4,re2wd1xx,finished,1,cot,gpt-4o,2,def,hr,6,0,...,0.000000,0.000000,3.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1435,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.800000,0.000000,0.000000,0.8
1436,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0
1437,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0
1438,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,0.800000,0.000000,0.000000,0.8
1439,fhxtlzl8,finished,6,tot,llama-32,2,llama32nosa,hr,6,0,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,1.0

In [8]:
# average the target_character
avg_df = normalized.groupby(['gpt_model', 'pe', 'n_self_alignment', 'Evaluation/llm_iteration', 'seed']).agg({'score': 'mean'}).reset_index()
avg_df['target_character'] = 'mean'
avg_df

,gpt_model,pe,n_self_alignment,Evaluation/llm_iteration,seed,score,target_character
0,gpt-4o,cot,0,1,0,0.000000,mean
1,gpt-4o,cot,0,1,1,0.004016,mean
2,gpt-4o,cot,0,1,2,0.000000,mean
3,gpt-4o,cot,0,1,3,0.004016,mean
4,gpt-4o,cot,0,1,4,0.005556,mean
...,...,...,...,...,...,...,...
631,llama-32,tot,5,6,5,0.387550,mean
632,llama-32,tot,5,6,6,1.000000,mean
633,llama-32,tot,5,6,7,0.000000,mean
634,llama-32,tot,5,6,8,0.366667,mean
635,llama-32,tot,5,6,9,0.500000,mean

In [9]:
df = pd.concat([df, avg_df], ignore_index=True)

In [10]:
import pandas as pd
import numpy as np
try:
    from scipy.stats import ttest_ind
    _HAS_SCIPY = True
except Exception:
    _HAS_SCIPY = False

def _welch_ttest_p(a, b):
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    a = a[~np.isnan(a)]
    b = b[~np.isnan(b)]
    if len(a) < 2 or len(b) < 2:
        return np.nan
    if _HAS_SCIPY:
        return ttest_ind(a, b, equal_var=False, nan_policy='omit').pvalue
    # fallback (정규 근사)
    ma, mb = a.mean(), b.mean()
    va, vb = a.var(ddof=1), b.var(ddof=1)
    na, nb = len(a), len(b)
    se2 = va/na + vb/nb
    if se2 == 0:
        return np.nan
    t = (ma - mb) / np.sqrt(se2)
    from math import erf, sqrt
    p = 2 * (1 - 0.5*(1 + erf(abs(t)/sqrt(2))))
    return p

In [11]:
def make_table(df: pd.DataFrame, ref_label: str = "PCGRLLM") -> pd.DataFrame:
    def agg_stats(sub_df, label):
        grouped = (
            sub_df.groupby(['gpt_model', 'pe'])
            .agg({'score': ['mean', 'std']})
            .reset_index()
        )
        grouped.columns = ['gpt_model', 'pe', f'{label} (mean)', f'{label} (std)']
        return grouped

    # 각 mode 정의
    zero_mask  = (df['n_self_alignment'] == 0) & (df['Evaluation/llm_iteration'] == 1)
    sa_mask    = (df['n_self_alignment'] == 5) & (df['Evaluation/llm_iteration'] == 1)
    fb_mask    = (df['n_self_alignment'] == 0) & (df['Evaluation/llm_iteration'] == 6)
    safb_mask  = (df['n_self_alignment'] == 5) & (df['Evaluation/llm_iteration'] == 6)

    base_df  = agg_stats(df[zero_mask], "Zero-shot")
    sa_df    = agg_stats(df[sa_mask],   "+Self-Alignment")
    fb_df    = agg_stats(df[fb_mask],   "+Feedback")
    safb_df  = agg_stats(df[safb_mask], "PCGRLLM")

    pk = ['gpt_model', 'pe']
    merged = (
        base_df.merge(sa_df, on=pk, how='outer')
               .merge(fb_df, on=pk, how='outer')
               .merge(safb_df, on=pk, how='outer')
    )

    # --- p-value 계산 ---
    p_rows = []
    for (g, p), _ in df.groupby(['gpt_model', 'pe']):
        sub = df[(df['gpt_model'] == g) & (df['pe'] == p)]

        zs_cur = sub[zero_mask]['score'].to_numpy()
        sa_cur = sub[sa_mask]['score'].to_numpy()
        ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준

        p_rows.append({
            'gpt_model': g,
            'pe': p,
            f'p: Zero-shot vs {ref_label}': _welch_ttest_p(zs_cur, ref),
            f'p: +Self-Alignment vs {ref_label}': _welch_ttest_p(sa_cur, ref),
        })

    pvals_df = pd.DataFrame(p_rows)
    merged = merged.merge(pvals_df, on=pk, how='left')
    return merged

In [12]:
def make_perf_table_by_targets(df, targets=(1, 2, 5, 6, 'mean')):
    tables = []
    for t in targets:
        
        sub = df[df['target_character'] == t]
        
        if sub.empty:
            continue
        tbl = make_table(sub)           # 이미 mean/std 포함 버전
        tbl.insert(0, 'target_character', t)
        tables.append(tbl)
    if not tables:
        return pd.DataFrame()
    return pd.concat(tables, ignore_index=True)

In [13]:
_df = df[df['gpt_model'] == 'gpt-4o']
perf_table_gpt = make_perf_table_by_targets(_df)
perf_table_gpt

/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준

,target_character,gpt_model,pe,Zero-shot (mean),Zero-shot (std),+Self-Alignment (mean),+Self-Alignment (std),+Feedback (mean),+Feedback (std),PCGRLLM (mean),PCGRLLM (std),p: Zero-shot vs PCGRLLM,p: +Self-Alignment vs PCGRLLM
0,1,gpt-4o,cot,0.064444,0.097942,0.013333,0.012172,0.011111,0.019245,0.093333,0.184357,0.767302,0.387325
1,1,gpt-4o,got,0.006667,0.006086,0.002222,0.004969,0.020000,0.004969,0.071111,0.130195,0.330665,0.302392
2,1,gpt-4o,tot,0.004444,0.009938,0.055556,0.087841,0.308889,0.378789,0.144444,0.122977,0.063374,0.228575
3,2,gpt-4o,cot,0.002222,0.004969,0.006667,0.009938,0.300000,0.322414,0.140000,0.313050,0.380798,0.394950
4,2,gpt-4o,got,0.004444,0.009938,0.002222,0.004969,0.173333,0.290657,0.248889,0.280608,0.123250,0.120775
5,2,gpt-4o,tot,0.000000,0.000000,0.000000,0.000000,0.251111,0.302724,0.073333,0.110163,0.210843,0.210843
6,5,gpt-4o,cot,0.000000,0.000000,0.420000,0.416733,0.026667,0.027889,0.793333,0.360863,0.007953,0.169163
7,5,gpt-4o,got,0.013333,0.018257,0.000000,0.000000,0.360000,0.497996,0.873333,0.247656,0.001433,0.001399
8,5,gpt-4o,tot,0.000000,0.000000,0.186667,0.317630,0.033333,0.074536,0.413333,0.536242,0.159884,0.444856
9,6,gpt-4o,cot,0.000000,0.000000,0.080000,0.144530,0.033333,0.047140,0.066667,0.062361,0.075130,0.856642
10,6,gpt-4o,got,0.106667,0.173845,0.026667,0.059628,0.000000,0.000000,0.466667,0.359011,0.091961,0.050902
11,6,gpt-4o,tot,0.000000,0.000000,0.253333,0.384130,0.000000,0.000000,0.573333,0.438051,0.042958,0.254870
12,mean,gpt-4o,cot,0.009686,0.019773,0.161508,0.206672,0.099076,0.120034,0.280864,0.305703,0.028803,0.348280
13,mean,gpt-4o,got,0.052659,0.131277,0.009088,0.021911,0.134863,0.199782,0.419922,0.328093,0.010320,0.005549
14,mean,gpt-4o,tot,0.000892,0.002677,0.157490,0.254103,0.161685,0.188946,0.352536,0.310253,0.005892,0.142107

In [14]:
_df = df[df['gpt_model'] == 'llama-32']
perf_table_llama = make_perf_table_by_targets(_df)
perf_table_llama

/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/opt/anaconda3/envs/pcgrl-jax/lib/python3.11/site-packages/scipy/stats/_axis_nan_policy.py:573: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  res = hypotest_fun_out(*samples, **kwds)
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:34: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  zs_cur = sub[zero_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:35: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  sa_cur = sub[sa_mask]['score'].to_numpy()
/var/folders/x_/2lt9k5kn52q43m1_z0kp7tfm0000gn/T/ipykernel_38313/2756133970.py:36: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ref    = sub[safb_mask]['score'].to_numpy()  # PCGRLLM 기준

,target_character,gpt_model,pe,Zero-shot (mean),Zero-shot (std),+Self-Alignment (mean),+Self-Alignment (std),+Feedback (mean),+Feedback (std),PCGRLLM (mean),PCGRLLM (std),p: Zero-shot vs PCGRLLM,p: +Self-Alignment vs PCGRLLM
0,1,llama-32,cot,0.146667,0.089374,0.273333,0.084474,0.026667,0.048177,0.293333,0.083370,0.027904,0.716120
1,1,llama-32,got,0.284444,0.294979,0.262222,0.100185,0.068889,0.065452,0.197778,0.117956,0.567308,0.379717
2,1,llama-32,tot,0.266667,0.215882,0.333333,0.000000,0.108889,0.121818,0.220000,0.159164,0.708252,0.186557
3,2,llama-32,cot,0.453333,0.260981,0.322222,0.296169,0.451111,0.349126,0.651111,0.397026,0.383311,0.178923
4,2,llama-32,got,0.013333,0.029814,0.353333,0.292647,0.544444,0.342738,0.568889,0.357754,0.025245,0.328668
5,2,llama-32,tot,0.340000,0.306775,0.191111,0.262866,0.362222,0.377908,0.506667,0.256953,0.379756,0.091200
6,5,llama-32,cot,0.293333,0.237346,0.306667,0.245402,0.420000,0.305141,0.733333,0.219848,0.016146,0.020279
7,5,llama-32,got,0.413333,0.220605,0.506667,0.366212,0.680000,0.279484,0.620000,0.306956,0.259701,0.610702
8,5,llama-32,tot,0.526667,0.253202,0.666667,0.217307,0.373333,0.291928,0.853333,0.136626,0.043231,0.149639
9,6,llama-32,cot,0.000000,0.000000,0.026667,0.027889,0.386667,0.454973,0.726667,0.386149,0.013609,0.015246
10,6,llama-32,got,0.006667,0.014907,0.006667,0.014907,0.233333,0.394405,0.406667,0.408520,0.093723,0.093723
11,6,llama-32,tot,0.000000,0.000000,0.026667,0.059628,0.206667,0.443722,0.193333,0.250998,0.160109,0.215108
12,mean,llama-32,cot,0.225862,0.144826,0.242139,0.105181,0.351799,0.156849,0.598409,0.281504,0.007188,0.008591
13,mean,llama-32,got,0.199595,0.201659,0.302002,0.134165,0.394894,0.258328,0.512558,0.239485,0.008713,0.039207
14,mean,llama-32,tot,0.277514,0.200527,0.302888,0.247314,0.222261,0.198416,0.466338,0.281392,0.108874,0.184853

In [15]:
import numpy as np
import pandas as pd

def df_to_latex_table(df: pd.DataFrame) -> str:
    """
    평균 ± 표준편차 형태로 출력,
    Zero-shot 포함 모든 조건 중 최고 mean은 bold,
    p < 0.05이면 마크 부여:
      - +Self-Alignment vs PCGRLLM : * (PCGRLLM 칸에 표시)
      - Zero-shot vs PCGRLLM       : † (PCGRLLM 칸에 표시)
    Target 값이 바뀔 때마다 \midrule 삽입
    셀 색상은 gray!n 사용, 셀 높이는 strut으로 고정
    """
    # 컬럼명 축약
    rename_map = {
        "p: Zero-shot vs PCGRLLM": "p(ZS)",
        "p: +Self-Alignment vs PCGRLLM": "p(SA)",
        "Zero-shot (mean)": "Zero-shot (ZS) (mean)",
        "Zero-shot (std)": "Zero-shot (ZS) (std)",
        "+Self-Alignment (mean)": "+Self-Alignment (SA) (mean)",
        "+Self-Alignment (std)": "+Self-Alignment (SA) (std)",
    }
    df = df.rename(columns={k: v for k, v in rename_map.items() if k in df.columns})

    mean_std_cols = [c for c in df.columns if "(mean)" in c]
    p_val_cols = [c for c in df.columns if c.startswith("p(")]
    cols = mean_std_cols + p_val_cols
    header = ["Target", "PE"] + [c.replace(" (mean)", "").replace(" (std)", "") for c in cols]

    # 정렬: Target 오름차순, PE = CoT → ToT → GoT
    pe_map = {"cot": "CoT", "tot": "ToT", "got": "GoT"}
    pe_order = {"CoT": 0, "ToT": 1, "GoT": 2}
    df["pe"] = df["pe"].map(pe_map)
    df = df.sort_values(
        by=["target_character", "pe"],
        key=lambda col: col.map(pe_order) if col.name == "pe" else col
    )

    # --- Global min/max for coloring ---
    all_means = df[mean_std_cols].to_numpy().flatten()
    vmin, vmax = np.nanmin(all_means), np.nanmax(all_means)

    def val_to_gray(val):
        """값을 vmin~vmax 구간에서 회색 강도로 매핑 (gray!5 ~ gray!30)"""
        if pd.isna(val):
            return "white"
        norm = (val - vmin) / (vmax - vmin + 1e-8)
        level = int(5 + norm * 25)  # 5~30 사이
        return f"gray!{level}"

    latex_rows = []
    prev_target = None
    for _, row in df.iterrows():
        curr_target = str(row.get("target_character", ""))

        if prev_target is not None and curr_target != prev_target:
            latex_rows.append("\\midrule")
        prev_target = curr_target

        row_entries = [curr_target, str(row["pe"])]

        # 최고 mean bold
        means = [row[c] for c in mean_std_cols]
        best_idx = int(np.nanargmax(means)) if len(means) > 0 else None
        best_label = mean_std_cols[best_idx].replace(" (mean)", "") if best_idx is not None else None

        for c in mean_std_cols:
            label = c.replace(" (mean)", "")
            mean = row[c]
            std = row[c.replace("(mean)", "(std)")]
            color = val_to_gray(mean)

            # strut으로 높이 고정
            base = f"\\cellcolor{{{color}}}\\rule{{0pt}}{{2.2ex}}\\color{{black}} {mean:.3f}$\\pm${{\\scriptsize {std:.3f}}}"

            # Bold
            if label == best_label:
                base = f"\\textbf{{{base}}}"

            # Significance mark → PCGRLLM 칸에만
            if label == "PCGRLLM":
                if "p(ZS)" in row and pd.notna(row["p(ZS)"]):
                    if row["p(ZS)"] < 0.05:
                        base += "$^{\\dagger}$"
                if "p(SA)" in row and pd.notna(row["p(SA)"]):
                    if row["p(SA)"] < 0.05:
                        base += "$^{*}$"

            row_entries.append(base)

        # p-value 셀 (숫자만, 중앙 정렬, 높이 통일)
        for c in p_val_cols:
            val = row[c]
            cell = "" if pd.isna(val) else f"\\rule{{0pt}}{{2.2ex}}{val:.3f}"
            row_entries.append(cell)

        latex_rows.append(" & ".join(row_entries) + " \\\\")

    # colspec: p-value 중앙정렬
    col_spec = "p{1.5cm}p{1.5cm}p{2.6cm}p{2.6cm}p{2.6cm}p{2.6cm}|cc"

    table = ""
    table += "\\begin{table*}\n"
    table += "\\centering\n"
    table += "\\caption{Performance by PE and Target. Significance marks: "
    table += "$^{*}$ for +Self-Alignment vs PCGRLLM, $^{\\dagger}$ for Zero-shot vs PCGRLLM.}\n"
    table += "\\label{tab:performance_pcgrllm}\n"
    table += f"\\begin{{tabular}}{{{col_spec}}}\n"
    table += "\\toprule\n"
    table += " & ".join(header) + " \\\\\n\\midrule\n"
    table += "\n".join(latex_rows) + "\n"
    table += "\\bottomrule\n\\end{tabular}\n"
    table += "\\end{table*}\n"
    return table

In [16]:
latex_str = df_to_latex_table(perf_table_gpt)
print(latex_str)

\begin{table*}
\centering
\caption{Performance by PE and Target. Significance marks: $^{*}$ for +Self-Alignment vs PCGRLLM, $^{\dagger}$ for Zero-shot vs PCGRLLM.}
\label{tab:performance_pcgrllm}
\begin{tabular}{p{1.5cm}p{1.5cm}p{2.6cm}p{2.6cm}p{2.6cm}p{2.6cm}|cc}
\toprule
Target & PE & Zero-shot (ZS) & +Self-Alignment (SA) & +Feedback & PCGRLLM & p(ZS) & p(SA) \\
\midrule
1 & CoT & \cellcolor{gray!6}\rule{0pt}{2.2ex}\color{black} 0.064$\pm${\scriptsize 0.098} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.013$\pm${\scriptsize 0.012} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.011$\pm${\scriptsize 0.019} & \textbf{\cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.093$\pm${\scriptsize 0.184}} & \rule{0pt}{2.2ex}0.767 & \rule{0pt}{2.2ex}0.387 \\
1 & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.004$\pm${\scriptsize 0.010} & \cellcolor{gray!6}\rule{0pt}{2.2ex}\color{black} 0.056$\pm${\scriptsize 0.088} & \textbf{\cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.309$\pm${\scriptsize 0.379}} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.144$\pm${\scriptsize 0.123} & \rule{0pt}{2.2ex}0.063 & \rule{0pt}{2.2ex}0.229 \\
1 & GoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.007$\pm${\scriptsize 0.006} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.002$\pm${\scriptsize 0.005} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.020$\pm${\scriptsize 0.005} & \textbf{\cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.071$\pm${\scriptsize 0.130}} & \rule{0pt}{2.2ex}0.331 & \rule{0pt}{2.2ex}0.302 \\
\midrule
2 & CoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.002$\pm${\scriptsize 0.005} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.007$\pm${\scriptsize 0.010} & \textbf{\cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.300$\pm${\scriptsize 0.322}} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.140$\pm${\scriptsize 0.313} & \rule{0pt}{2.2ex}0.381 & \rule{0pt}{2.2ex}0.395 \\
2 & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \textbf{\cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.251$\pm${\scriptsize 0.303}} & \cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.073$\pm${\scriptsize 0.110} & \rule{0pt}{2.2ex}0.211 & \rule{0pt}{2.2ex}0.211 \\
2 & GoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.004$\pm${\scriptsize 0.010} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.002$\pm${\scriptsize 0.005} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.173$\pm${\scriptsize 0.291} & \textbf{\cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.249$\pm${\scriptsize 0.281}} & \rule{0pt}{2.2ex}0.123 & \rule{0pt}{2.2ex}0.121 \\
\midrule
5 & CoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!17}\rule{0pt}{2.2ex}\color{black} 0.420$\pm${\scriptsize 0.417} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.027$\pm${\scriptsize 0.028} & \textbf{\cellcolor{gray!27}\rule{0pt}{2.2ex}\color{black} 0.793$\pm${\scriptsize 0.361}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.008 & \rule{0pt}{2.2ex}0.169 \\
5 & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!10}\rule{0pt}{2.2ex}\color{black} 0.187$\pm${\scriptsize 0.318} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.033$\pm${\scriptsize 0.075} & \textbf{\cellcolor{gray!16}\rule{0pt}{2.2ex}\color{black} 0.413$\pm${\scriptsize 0.536}} & \rule{0pt}{2.2ex}0.160 & \rule{0pt}{2.2ex}0.445 \\
5 & GoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.013$\pm${\scriptsize 0.018} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.360$\pm${\scriptsize 0.498} & \textbf{\cellcolor{gray!29}\rule{0pt}{2.2ex}\color{black} 0.873$\pm${\scriptsize 0.248}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.001 & \rule{0pt}{2.2ex}0.001 \\
\midrule
6 & CoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \textbf{\cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.080$\pm${\scriptsize 0.145}} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.033$\pm${\scriptsize 0.047} & \cellcolor{gray!6}\rule{0pt}{2.2ex}\color{black} 0.067$\pm${\scriptsize 0.062} & \rule{0pt}{2.2ex}0.075 & \rule{0pt}{2.2ex}0.857 \\
6 & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.253$\pm${\scriptsize 0.384} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \textbf{\cellcolor{gray!21}\rule{0pt}{2.2ex}\color{black} 0.573$\pm${\scriptsize 0.438}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.043 & \rule{0pt}{2.2ex}0.255 \\
6 & GoT & \cellcolor{gray!8}\rule{0pt}{2.2ex}\color{black} 0.107$\pm${\scriptsize 0.174} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.027$\pm${\scriptsize 0.060} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \textbf{\cellcolor{gray!18}\rule{0pt}{2.2ex}\color{black} 0.467$\pm${\scriptsize 0.359}} & \rule{0pt}{2.2ex}0.092 & \rule{0pt}{2.2ex}0.051 \\
\midrule
mean & CoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.010$\pm${\scriptsize 0.020} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.162$\pm${\scriptsize 0.207} & \cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.099$\pm${\scriptsize 0.120} & \textbf{\cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.281$\pm${\scriptsize 0.306}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.029 & \rule{0pt}{2.2ex}0.348 \\
mean & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.001$\pm${\scriptsize 0.003} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.157$\pm${\scriptsize 0.254} & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.162$\pm${\scriptsize 0.189} & \textbf{\cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.353$\pm${\scriptsize 0.310}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.006 & \rule{0pt}{2.2ex}0.142 \\
mean & GoT & \cellcolor{gray!6}\rule{0pt}{2.2ex}\color{black} 0.053$\pm${\scriptsize 0.131} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.009$\pm${\scriptsize 0.022} & \cellcolor{gray!8}\rule{0pt}{2.2ex}\color{black} 0.135$\pm${\scriptsize 0.200} & \textbf{\cellcolor{gray!17}\rule{0pt}{2.2ex}\color{black} 0.420$\pm${\scriptsize 0.328}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.010 & \rule{0pt}{2.2ex}0.006 \\
\bottomrule
\end{tabular}
\end{table*}

In [17]:
latex_str = df_to_latex_table(perf_table_llama)
print(latex_str)

\begin{table*}
\centering
\caption{Performance by PE and Target. Significance marks: $^{*}$ for +Self-Alignment vs PCGRLLM, $^{\dagger}$ for Zero-shot vs PCGRLLM.}
\label{tab:performance_pcgrllm}
\begin{tabular}{p{1.5cm}p{1.5cm}p{2.6cm}p{2.6cm}p{2.6cm}p{2.6cm}|cc}
\toprule
Target & PE & Zero-shot (ZS) & +Self-Alignment (SA) & +Feedback & PCGRLLM & p(ZS) & p(SA) \\
\midrule
1 & CoT & \cellcolor{gray!9}\rule{0pt}{2.2ex}\color{black} 0.147$\pm${\scriptsize 0.089} & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.273$\pm${\scriptsize 0.084} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.027$\pm${\scriptsize 0.048} & \textbf{\cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.293$\pm${\scriptsize 0.083}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.028 & \rule{0pt}{2.2ex}0.716 \\
1 & ToT & \cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.267$\pm${\scriptsize 0.216} & \textbf{\cellcolor{gray!14}\rule{0pt}{2.2ex}\color{black} 0.333$\pm${\scriptsize 0.000}} & \cellcolor{gray!8}\rule{0pt}{2.2ex}\color{black} 0.109$\pm${\scriptsize 0.122} & \cellcolor{gray!11}\rule{0pt}{2.2ex}\color{black} 0.220$\pm${\scriptsize 0.159} & \rule{0pt}{2.2ex}0.708 & \rule{0pt}{2.2ex}0.187 \\
1 & GoT & \textbf{\cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.284$\pm${\scriptsize 0.295}} & \cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.262$\pm${\scriptsize 0.100} & \cellcolor{gray!7}\rule{0pt}{2.2ex}\color{black} 0.069$\pm${\scriptsize 0.065} & \cellcolor{gray!10}\rule{0pt}{2.2ex}\color{black} 0.198$\pm${\scriptsize 0.118} & \rule{0pt}{2.2ex}0.567 & \rule{0pt}{2.2ex}0.380 \\
\midrule
2 & CoT & \cellcolor{gray!18}\rule{0pt}{2.2ex}\color{black} 0.453$\pm${\scriptsize 0.261} & \cellcolor{gray!14}\rule{0pt}{2.2ex}\color{black} 0.322$\pm${\scriptsize 0.296} & \cellcolor{gray!18}\rule{0pt}{2.2ex}\color{black} 0.451$\pm${\scriptsize 0.349} & \textbf{\cellcolor{gray!24}\rule{0pt}{2.2ex}\color{black} 0.651$\pm${\scriptsize 0.397}} & \rule{0pt}{2.2ex}0.383 & \rule{0pt}{2.2ex}0.179 \\
2 & ToT & \cellcolor{gray!14}\rule{0pt}{2.2ex}\color{black} 0.340$\pm${\scriptsize 0.307} & \cellcolor{gray!10}\rule{0pt}{2.2ex}\color{black} 0.191$\pm${\scriptsize 0.263} & \cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.362$\pm${\scriptsize 0.378} & \textbf{\cellcolor{gray!19}\rule{0pt}{2.2ex}\color{black} 0.507$\pm${\scriptsize 0.257}} & \rule{0pt}{2.2ex}0.380 & \rule{0pt}{2.2ex}0.091 \\
2 & GoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.013$\pm${\scriptsize 0.030} & \cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.353$\pm${\scriptsize 0.293} & \cellcolor{gray!20}\rule{0pt}{2.2ex}\color{black} 0.544$\pm${\scriptsize 0.343} & \textbf{\cellcolor{gray!21}\rule{0pt}{2.2ex}\color{black} 0.569$\pm${\scriptsize 0.358}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.025 & \rule{0pt}{2.2ex}0.329 \\
\midrule
5 & CoT & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.293$\pm${\scriptsize 0.237} & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.307$\pm${\scriptsize 0.245} & \cellcolor{gray!17}\rule{0pt}{2.2ex}\color{black} 0.420$\pm${\scriptsize 0.305} & \textbf{\cellcolor{gray!26}\rule{0pt}{2.2ex}\color{black} 0.733$\pm${\scriptsize 0.220}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.016 & \rule{0pt}{2.2ex}0.020 \\
5 & ToT & \cellcolor{gray!20}\rule{0pt}{2.2ex}\color{black} 0.527$\pm${\scriptsize 0.253} & \cellcolor{gray!24}\rule{0pt}{2.2ex}\color{black} 0.667$\pm${\scriptsize 0.217} & \cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.373$\pm${\scriptsize 0.292} & \textbf{\cellcolor{gray!29}\rule{0pt}{2.2ex}\color{black} 0.853$\pm${\scriptsize 0.137}}$^{\dagger}$ & \rule{0pt}{2.2ex}0.043 & \rule{0pt}{2.2ex}0.150 \\
5 & GoT & \cellcolor{gray!17}\rule{0pt}{2.2ex}\color{black} 0.413$\pm${\scriptsize 0.221} & \cellcolor{gray!19}\rule{0pt}{2.2ex}\color{black} 0.507$\pm${\scriptsize 0.366} & \textbf{\cellcolor{gray!24}\rule{0pt}{2.2ex}\color{black} 0.680$\pm${\scriptsize 0.279}} & \cellcolor{gray!23}\rule{0pt}{2.2ex}\color{black} 0.620$\pm${\scriptsize 0.307} & \rule{0pt}{2.2ex}0.260 & \rule{0pt}{2.2ex}0.611 \\
\midrule
6 & CoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.027$\pm${\scriptsize 0.028} & \cellcolor{gray!16}\rule{0pt}{2.2ex}\color{black} 0.387$\pm${\scriptsize 0.455} & \textbf{\cellcolor{gray!26}\rule{0pt}{2.2ex}\color{black} 0.727$\pm${\scriptsize 0.386}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.014 & \rule{0pt}{2.2ex}0.015 \\
6 & ToT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.000$\pm${\scriptsize 0.000} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.027$\pm${\scriptsize 0.060} & \textbf{\cellcolor{gray!11}\rule{0pt}{2.2ex}\color{black} 0.207$\pm${\scriptsize 0.444}} & \cellcolor{gray!10}\rule{0pt}{2.2ex}\color{black} 0.193$\pm${\scriptsize 0.251} & \rule{0pt}{2.2ex}0.160 & \rule{0pt}{2.2ex}0.215 \\
6 & GoT & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.007$\pm${\scriptsize 0.015} & \cellcolor{gray!5}\rule{0pt}{2.2ex}\color{black} 0.007$\pm${\scriptsize 0.015} & \cellcolor{gray!11}\rule{0pt}{2.2ex}\color{black} 0.233$\pm${\scriptsize 0.394} & \textbf{\cellcolor{gray!16}\rule{0pt}{2.2ex}\color{black} 0.407$\pm${\scriptsize 0.409}} & \rule{0pt}{2.2ex}0.094 & \rule{0pt}{2.2ex}0.094 \\
\midrule
mean & CoT & \cellcolor{gray!11}\rule{0pt}{2.2ex}\color{black} 0.226$\pm${\scriptsize 0.145} & \cellcolor{gray!12}\rule{0pt}{2.2ex}\color{black} 0.242$\pm${\scriptsize 0.105} & \cellcolor{gray!15}\rule{0pt}{2.2ex}\color{black} 0.352$\pm${\scriptsize 0.157} & \textbf{\cellcolor{gray!22}\rule{0pt}{2.2ex}\color{black} 0.598$\pm${\scriptsize 0.282}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.007 & \rule{0pt}{2.2ex}0.009 \\
mean & ToT & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.278$\pm${\scriptsize 0.201} & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.303$\pm${\scriptsize 0.247} & \cellcolor{gray!11}\rule{0pt}{2.2ex}\color{black} 0.222$\pm${\scriptsize 0.198} & \textbf{\cellcolor{gray!18}\rule{0pt}{2.2ex}\color{black} 0.466$\pm${\scriptsize 0.281}} & \rule{0pt}{2.2ex}0.109 & \rule{0pt}{2.2ex}0.185 \\
mean & GoT & \cellcolor{gray!10}\rule{0pt}{2.2ex}\color{black} 0.200$\pm${\scriptsize 0.202} & \cellcolor{gray!13}\rule{0pt}{2.2ex}\color{black} 0.302$\pm${\scriptsize 0.134} & \cellcolor{gray!16}\rule{0pt}{2.2ex}\color{black} 0.395$\pm${\scriptsize 0.258} & \textbf{\cellcolor{gray!20}\rule{0pt}{2.2ex}\color{black} 0.513$\pm${\scriptsize 0.239}}$^{\dagger}$$^{*}$ & \rule{0pt}{2.2ex}0.009 & \rule{0pt}{2.2ex}0.039 \\
\bottomrule
\end{tabular}
\end{table*}